version: "3"

services:
  api-server:
    build:
      context: .
    container_name: api-server
    image: api-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://host.docker.internal:27017/Users
      - SECRET_TOKEN_KEY=1q2w3e4r5t6y7u8i9o0p_prod
    volumes:
      - ./logs:/logs
    networks:
      - app-network
    ports:
      - "3000:3000"
  mongo:
    image: mongo:5.0
    container_name: mongo-dev
    restart: always
    networks:
      - app-network
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
